spring.application.name=vwa-edurecords

spring.datasource.url=jdbc:postgresql://localhost:5432/vwa_edurecords
spring.datasource.username=postgres
spring.datasource.password=332003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
